//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebArtefactos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Linea
    {
        public string Lin_cod { get; set; }
        public string Lin_nom { get; set; }
    }
}
