//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebArtefactos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bdArtefactoEntities1 : DbContext
    {
        public bdArtefactoEntities1()
            : base("name=bdArtefactoEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Artefacto> Artefacto { get; set; }
        public DbSet<Clientes> Clientes { get; set; }
        public DbSet<Linea> Linea { get; set; }
        public DbSet<proforma> proforma { get; set; }
    }
}
