//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebArtefactos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class proforma
    {
        public string nro_pro { get; set; }
        public string cli_cod { get; set; }
        public string art_cod { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<int> tipo_ven { get; set; }
        public Nullable<decimal> Interes { get; set; }
        public Nullable<decimal> saldo { get; set; }
        public Nullable<decimal> cuota { get; set; }
    }
}
